aliases:
    chamber-iluma: aws-vault exec iluma -- chamber
    chamber-iluma-staging: aws-vault exec iluma-staging -- chamber
    fleeks: cd ~/.local/share/fleek
    nx: NIXPKGS_ALLOW_UNFREE=1 nix-shell -p
bling: low
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - k9s
    - kubectl
    - aws-vault
    - chamber
    - awscli2
    - postgresql
    - newman
    - s-tui
    - stress
    - neofetch
    - helm
    - gnomeExtensions.transparent-top-bar-adjustable-transparency
    - gnomeExtensions.tailscale-status
    - gnomeExtensions.gtile
    - gnomeExtensions.power-profile-switcher
    - gnomeExtensions.ideapad-controls
    - gnomeExtensions.screen-rotate
    - gnomeExtensions.clipboard-indicator
    - noisetorch
    - jetbrains.idea-ultimate
    - postman
    - android-studio
    - android-tools
    - bundletool
    - bmon
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
    - zsh.oh-my-zsh
shell: zsh
systems:
    - arch: x86_64
      hostname: yoga7
      os: linux
      username: xendit
    - arch: x86_64
      hostname: yoga7
      os: linux
      username: gz
    - arch: x86_64
      hostname: office-pc
      os: linux
      username: gz
unfree: true
users:
    - email: paulfauchon@xendit.co
      name: xendit
      ssh_private_key_file: ~/.ssh/id_rsa
      ssh_public_key_file: ~/.ssh/id_rsa.pub
      username: xendit
    - email: paul@fauchon.dev
      name: gz
      ssh_private_key_file: ~/.ssh/id_rsa
      ssh_public_key_file: ~/.ssh/id_rsa.pub
      username: gz
