aliases:
    chamber-iluma: aws-vault exec iluma -- chamber
    chamber-iluma-staging: aws-vault exec iluma-staging -- chamber
    fleeks: cd ~/.local/share/fleek
bling: high
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
packages:
    - k9s
    - kubectl
    - aws-vault
    - chamber
    - awscli2
    - postgresql
    - newman
    - s-tui
    - stress
    - neofetch
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: zsh
systems:
    - arch: x86_64
      hostname: yoga7
      os: linux
      username: xendit
unfree: true
users:
    - email: paulfauchon@xendit.co
      name: xendit
      ssh_private_key_file: ~/.ssh/id_rsa
      ssh_public_key_file: ~/.ssh/id_rsa.pub
      username: xendit
